# Generated by Django 5.1.7 on 2025-04-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=150)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(max_length=10000)),
            ],
        ),
    ]
