# Generated by Django 5.2 on 2025-05-01 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.CharField(default=0)),
                ('province', models.CharField(choices=[('KwaZulu-Natal', 'KZN'), ('Limpopo', 'LP'), ('Mpumalanga', 'MP'), ('Gauteng', 'GP'), ('Western Cape', 'WC'), ('Eastern Cape', 'EC'), ('Northern Cape', 'NC'), ('Free State', 'FS'), ('North West', 'NW')], max_length=100)),
                ('postal_code', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
